[book]
authors = ["the skiftOS Develpers"]
language = "en"
multilingual = false
src = "."
title = "SkiftOS Developer Manual"

[output.html]
default-theme = "skift-light"
preferred-dark-theme = "skift-dark"
